config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :bikes
  resources :bookings

  # get "/about", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  SIZE = %w[51 53 55 57 60]
  validates :size, inclusion: { within: SIZE,  message: "%{value} is not in the list. It must be #{SIZE}"}, presence: true
  validates :user, presence: true
  validates :brand, presence: true
  validates :color, presence: true
  validates :price, presence: true
  validates :address, presence: true #added address field for geocoded 24.02.23

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :address, presence: true
  CATEGORY = %w[City Race MTB Gravel eBike]
  validates :category, inclusion: { within: CATEGORY, message: "%{value} is not in the list. It must be #{CATEGORY}" }, presence: true
  validates :photo, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_brand_and_address,
  against: [ :brand, :address ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }


end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :start_date, :end_date, presence: true
  belongs_to :user
  belongs_to :bike
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, :first_name, :last_name, :password, presence: true
  validates :email, uniqueness: true
  has_many :bikes
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: :home
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  def index
    @bikes = Bike.all
    # The `geocoded` scope filters only bikes with coordinates 24.02.23
    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {bike: bike}),
        marker_html: render_to_string(partial: "marker", locals: {bike: bike})
      }
    end
    #pg_search gem added 25.02.23
    if params[:id].present?
      @bikes = Bike.search_by_brand_and_address(params[:id])
    else
      @bikes = Bike.all
    end
  end

  def show
    # @bike = bike_params[:id]
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user # we need to assign the creation of a bike to a user
    if @bike.save # we use '!' to know if there is an error
      redirect_to bikes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @bike.update(bike_params)
      redirect_to bike_path(@bike) # what does the _path do? It's a helper method that generate a url to the show action
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy # doesn't work yet(!)
    @bike.destroy
    redirect_to bikes_path # this is going to direct us to the show page? >> ask TA, how does it work?
  end

  private

  def bike_params
    params.require(:bike).permit(:brand, :color, :size, :price, :category, :address, :photo)
  end

  def set_bike
    @bike = Bike.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all.includes(:bike)
  end

  def new
    #bike = Bike.find_by(brand: params[:bike_brand])
    #@booking = Booking.new #(bike: bike)
    @booking = Booking.new
    @bike = Bike.find(params[:bike_id])
    @booking.bike = @bike
  end

  def create
    @bike = Bike.find(params[:booking][:bike_id])
    @booking = @bike.bookings.build(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: "Booking created successfully!"
    else
      render :new
    end
  end

  def show
    @bike = @booking.bike
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking) # what does the _path do? It's a helper method that generate a url to the show action
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :bike_id) # deleted :total_price
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<h2><%= bike.brand %></h2>
<p><%= bike.address %></p>

app/views/bikes/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

<div class="badge rounded-pill bg-primary fs-6">
  <%= bike.brand %>
</div>

app/views/bikes/edit.html.erb
<div class="container">
  <%= simple_form_for @bike do |f| %>
    <%= f.input :photo, as: :file %>
    <%= f.input :brand %>
    <%= f.input :color %>
    <%= f.input :size %>
    <%= f.input :category %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bikes/index.html.erb
<div class="container">
  <div class="card-map mx-auto m-3" style="width: 80%; height: 300px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<div class="container">
  <div class="row">
    <% @bikes.each do |b| %>
      <div class="col-lg-2 col-md-4 col-sm-6 mb-4">
        <a href="<%= bike_path(b) %>">
          <div class="product-box shadow">
            <div class="product-inner-box position-relative">
              <div class="icons">
                <button class="btn btn-link position-absolute top-0 end-0">
                  <i class="fas fa-heart heart"></i>
                </button>
              </div>
              <%= cl_image_tag b.photo.key, class: "card-img-top", width: 400, height: 300, crop: :lfill, gravity: :center %>
              <div class="product-info">
                  <div class="product-name">
                    <h4 class="card-title"><%= b.brand %></h4>
                  </div>
                  <div class="product-address">
                    City: <span><%= b.address %></span>
                  </div>
                  <div>
                    Size: <span><%= b.size %></span>
                  </div>
                  <div>
                    Color: <span><%= b.color %></span>
                  </div>
                  <div class="product-price">
                    $<span><%= b.price %></span> per day
                  </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/bikes/new.html.erb
<div class="container">
  <%= simple_form_for @bike do |f| %>
    <%= f.input :photo, as: :file %>
    <%= f.input :brand %>
    <%= f.input :color %>
    <%= f.input :size %>
    <%= f.input :category %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bikes/show.html.erb
<div class="container">
  <h3><%= @bike.brand %></h3>
  <p><%#= @bike.photo %></p>
  <p><%= @bike.color %></p>
  <p><%= @bike.size %></p>
  <p><%= @bike.category %></p>
  <p><%= @bike.address %></p>
  <p><%= @bike.price %></p>

  <button type="button" class="btn btn-outline-success" data-toggle="button" aria-pressed="false" autocomplete="off">

    <%= link_to "Book the bike",
      new_booking_path(bike_id: @bike.id),
      data: {turbo_confirm: "Are you sure you want to book"}
    %>
  </button>
  <button type="button" class="btn btn-outline-info" data-toggle="button" aria-pressed="false" autocomplete="off">

    <%= link_to "update",
      edit_bike_path(@bike),
      data: {turbo_confirm: "Are you sure you want to update?"}
    %>
  </button>

  <button type="button" class="btn btn-outline-danger" data-toggle="button" aria-pressed="false" autocomplete="off">

    <%= link_to "Delete",
      bike_path(@bike),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %>
  </button>
</div>

app/views/bookings/edit.html.erb
<div class="container">
  <%= simple_form_for @booking do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :bike_id, collection: Bike.all.map{ |b| [b.brand, b.id] } %>
  <%= f.submit %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container mx-auto m-3">
  <div class="row">
    <% @bookings.each do |b| %>
      <div class="col-lg-2 col-md-4 col-sm-6 mb-4">
        <a href="<%= booking_path(b) %>">
          <div class="product-box shadow">
            <div class="product-inner-box position-relative">
              <div class="icons">
                <button class="btn btn-link position-absolute top-0 end-0">
                  <i class="fas fa-heart heart"></i>
                </button>
              </div>
              <%= cl_image_tag b.bike.photo.key, class: "card-img-top", width: 400, height: 300, crop: :lfill, gravity: :center %>
              <div class="product-info">
                  <div class="product-name">
                    <h4 class="card-title"><%= b.bike.brand %></h4>
                  </div>
                  <div class="product-address">
                    City: <span><%= b.bike.address %></span>
                  </div>
                  <div>
                    Size: <span><%= b.bike.size %></span>
                  </div>
                  <div>
                    Color: <span><%= b.bike.color %></span>
                  </div>
                  <div class="product-price">
                    <% b_amount_days = (b.end_date - b.start_date) / 86400 %>
                    $<span><%= b.total_price = b_amount_days * b.bike.price %> for <%= b_amount_days.to_i %> days of rent </span>
                  </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <%= simple_form_for @booking do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :bike_id, collection: Bike.all.map{ |b| [b.brand, b.id] } %>
  <%= f.submit %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="back-line">
    <a href="/bookings" class="back-button">&#8249;</a>
    <span class="back-title">Back</span>
  </div>
</div>

<div class ="container col-sm-4 mt-4">
  <h4 class="mb-3">Your bike</h4>

  <div class="d-flex justify-content-between mb-3">
      <h5>Dates: <%= @booking.start_date.strftime("%d %b") %> - <%= @booking.end_date.strftime("%d %b") %> </h5>
      <div>
        <% b_amount_days = (@booking.end_date.day - @booking.start_date.day) / 86400 %>
        <h5>Total price: $<%= @booking.total_price = b_amount_days.to_i * @booking.bike.price * (-2) %></h5>
      </div>
  </div>

  <div class="d-flex justify-content-center mb-3"><%= cl_image_tag @booking.bike.photo.key, class: "card-img-top", width: 400, height: 300, crop: :lfill, gravity: :center %>
  </div>

  <%= link_to "Delete booking",
    booking_path(@booking),
    # the _path is taking us to the "booking" url which is making a request to the URI bookings/id.
    # to find the :id we are calling the booking instance, @booking
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>

  <%= link_to "Update booking",
    edit_booking_path(@booking),
    data: {turbo_confirm: "Are you sure you want to update?"}
  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnbbikes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="neato-header">
  <h2>go explore</h2>
  <h1>AirBnB Bikes</h1>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/bikes", class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dixcpm3ie/image/upload/v1677527913/home2_k24jsu.png" %>
    <% end %>
    <div >
      <%= form_with url: bikes_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :id,
      params[:id],
      class: "form-control",
      placeholder: "Find a bike"
      %>
      <%= submit_tag "Search", class: "btn btn-outline-danger" %>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to "http://www.instagram.com/bikesabnb", class: "navbar-brand", :title => "Follow airbnbbikes on instagram", target: :_blank do %>
          <%= image_tag "https://res.cloudinary.com/dixcpm3ie/image/upload/v1677543967/14581_erknuz.jpg" %>
        <% end %>
        <%= link_to "http://www.twitter.com", class: "navbar-brand", :title => "Follow airbnbbikes on Twitter", target: :_blank do %>
          <%= image_tag "https://res.cloudinary.com/dixcpm3ie/image/upload/v1677544403/8578_bekesi.png" %>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
           <li class="nav-item active">
            <%= link_to "Bikes", bikes_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Post a Bike", new_bike_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>